# Generated by Django 2.2.4 on 2020-01-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_volounteerattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='volounteer',
            name='absent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='volounteer',
            name='present',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='volounteer',
            name='volounteer_gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=2, null=True),
        ),
    ]
