# Generated by Django 2.2.4 on 2020-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200101_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English')], default='Maths', max_length=20),
        ),
    ]
