# Generated by Django 2.2.4 on 2020-01-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200102_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(max_length=100000)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Volounteer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_comment', models.TextField(max_length=100000)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Volounteer')),
                ('on_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Post')),
            ],
        ),
    ]
