# Generated by Django 2.2.4 on 2020-01-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_comment_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='on_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(),
        ),
    ]
