# Generated by Django 2.2.4 on 2020-03-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20200108_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='student/displaypic'),
        ),
        migrations.AddField(
            model_name='volounteer',
            name='volounteer_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/displaypic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Volounteer'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_on', models.DateTimeField()),
                ('visit_comments', models.TextField(blank=True, max_length=100000, null=True)),
                ('visit_outcome', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Need Discussion', 'Need Discussion'), ('Another Visit', 'Another Visit')], default='Another Visit', max_length=27)),
                ('visit_final', models.PositiveIntegerField(blank=True, null=True)),
                ('visit_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Volounteer')),
                ('visit_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
                ('visit_with', models.ManyToManyField(related_name='volounteer_visitors', to='attendance.Volounteer')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.School'),
        ),
    ]
