# Generated by Django 2.2.4 on 2020-03-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_student_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
