# Generated by Django 2.2.4 on 2020-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20200304_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Attendance', 'Attendance'), ('Visit', 'Visit')], max_length=200, null=True),
        ),
    ]
