# Generated by Django 2.2.4 on 2020-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_student_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
