# Generated by Django 2.2.4 on 2020-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20200305_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_discussion',
            field=models.CharField(choices=[('Discussed', 'Discussed'), ('Not Discussed', 'Not Discussed')], default='Not Discussed', max_length=90),
        ),
    ]
